# サンプルファイルです。個別に設定してください。
# カレンダ定義
cals:
  # サイボウズ用プラグイン ###############################################################
  - name: サイボウズ
    file: cybozu

    # サイボウズ画面を小さくしてボタン押下時の範囲外を抑制 (keepdriver=0のとき有効)
    devscale: '0.7'

    # ログイン情報
    serv: "**YourServer**"          # ログインサーバ名
    user: "**YourUser**"            # ログイン用ユーザ
    pass: "**YourPass**"            # ログイン用パスワード

    # 検索範囲(当日～n日後まで)
    range: 3
    
    # 時刻がなくても、予定文が以下にマッチすれば終日扱い
    alldaysw:                 # 先頭一致のリスト
      - 休み
    alldayre: ".*外出.*"  # 正規表現指定
    alltime: 10:00-22:00

    # 取得データが0件の場合の処理
    checkzero: 0   # 取得データが0の時に処理を中断する(0:継続、1:停止、2:確認)

    # 検索対象のグループを列挙(グループ内で部屋名と担当者名が混在しても構わない)
    group:
      - name: 部屋グループ
        target: # 部屋グループの中の抽出対象の部屋名を列挙
        - 煙草部屋
        - 帝鑑
        - 連歌

      - name: 担当グループ
        target: # 担当グループの中の抽出対象の担当者名を列挙
        - 織田
        - 豊臣
        - 徳川
        - 井伊

  # Airリザーブ用プラグイン #############################################################
  - name: Airリザーブ
    file: airr

    # サイボウズ画面を小さくしてボタン押下時の範囲外を抑制 (keepdriver=0のとき有効)
    devscale: '0.7'

    # ログイン情報
    user: "**YourUser**"            # ログイン用ユーザ
    pass: "**YourPass**"            # ログイン用パスワード

    # 検索範囲(当日～n日後まで)
    range: 3

    # 取得データが0件の場合の処理
    checkzero:      2   # 取得データが0の時に処理を中断する(0:継続、1:停止、2:確認)
    checkgroupzero: 2   # グループ単位の取得データが0の時に処理を中断する(0:継続、1:停止、2:確認)
    
    # 検索対象のグループ(検索対象のAirリザーブ拠点グループを指定)
    group:
      - 江戸
      - 大阪

    # ルームリソース（Airリザーブで選択可能な部屋名。人名と異なる事）
    # ※ Airリザーブ仕様では、部屋名と同じ人名があると、リソースを区別できない
    roomres:
      - 合議室
      - 帝鑑之間
      - 連歌之間
      - 不使用

    # 追加/削除をするかの設定
    skipadd: 0  # 1なら追加処理をスキップ
    skipdel: 0  # 1なら削除処理をスキップ

    # 追加削除前に確認するかの設定
    waitadd: 1  # 1なら追加の確定前に確認
    waitdel: 1  # 1なら削除の確定前に確認
    waitbtnerror: 1 # 1なら追加ボタンの押下エラー時に手動継続確認

    # 追加時のメニュー、セイ
    addmenu:  サイボウズ
    addsei:   ・ # 全角カナか「・」しか入力できない

    # 削除処理時の選択
    delreason: 店舗都合

# 同期処理用プラグイン
sync:
  # サイボウズ→Airリザーブ同期用プラグイン #####################################################
  - name:  マージ処理
    file:  cb2ar

    # 事務所と部屋の対応付け(左の部屋名はサイボウズ名、右の部屋名はAirリザーブ名)
    # 事務所名は、Airリザーブで検索できる名前であること
    room:
      帝鑑:     [江戸, 帝鑑之間]
      連歌:     [江戸, 連歌之間]
      煙草部屋: [大阪, 合議室]

    # 事務所と人の対応付け (左はサイボウズのsplitで取得できる空白文字までの名前)
    # 人の名前は(roomと異なり)サイボウズとAirリザーブで一致するため、追加情報は不要
    person:
      徳川: 江戸
      井伊: 江戸
      豊臣: 大阪
      織田: 岐阜

    # 以下の人は、部屋予約が不要な場合はAirリザーブに登録しない
    # ※部屋予約が不要 → eject対象外の誰かと共通の会議を持ち、その人が部屋を確保している場合
    eject:
      - 明智

    # 人/部屋と事務所のマッチングができなかった時の選択肢
    noroom:   不使用
    noperson: 無人

    # 特定曜日のSUMM(拠点@部屋@人)を変更
    # 対象は[1:月, 2:火, 4:水, 8:木, 16:金, 32:土, 64:日] の和で指定 (例: 土日: 32 + 64 = 96)
    weeksumm:
      - [96, "(江戸@.*@)(徳川|井伊)", "\\1鳥居"] # 週末の徳川or井伊予定はAirリザーブ上は鳥居をシフトで入れる

    # 無視する予定。サイボウズの予定名から正規表現で一致するものを無視。
    skipdesc: ".*（仮予定）.*"

    # 削除扱いの予定。サイボウズの予定名の先頭一致で指定。(無視と扱いは同等)
    deldesc:
      - 日程変更
      - キャンセル

    # 自動入力したときのキーワード(addmenuと同じで良い)
    automenu:  サイボウズ

     # 予約比較方法
    compdesc: 1 # 0:開始時刻/終了時刻/人/場所のみ比較、1:左記に加えてdescription(最大先頭40文字)まで含める

    
# その他オプション ####################################################################
waitsync:       1   # 同期処理を開始する前に確認する
waitcopy:       1   # コピー処理を開始する前に確認する
waitset:        1   # カレンダ設定処理を開始する前に確認する
skipget:        0 # 取得処理をスキップして保存されたマージファイルを解析(デバッグ用)

keepdriver:     0   # ブラウザをプログラム開始～終了まで常駐したままにする(0:プラグインごとに必要に応じて起動)
devscale:       '0.7' # 画面を小さくしてボタン押下時の範囲外を抑制 (keepdriver=1のとき有効)
