# サンプルファイルです。個別に設定してください。
# カレンダ定義
cals:
  # サイボウズ用プラグイン ###############################################################
  - name: サイボウズ
    file: cybozu

    # ログイン情報
    serv: "**YourServer**"          # ログインサーバ名
    user: "**YourUser**"            # ログイン用ユーザ
    pass: "**YourPass**"            # ログイン用パスワード

    # 検索範囲(当日～n日後まで)
    range: 3
    
    # 時刻がなくても、予定文が以下のいずれかと先頭一致なら終日扱い
    allday:
      - 休み
    alltime: 10:00-18:00

    # 検索対象のグループ
    group:
      - name: 拠点
        target:
        - 岐阜
        - 大阪
        - 江戸

      - name: 担当者
        target:
        - 織田
        - 豊臣
        - 徳川
        - 井伊

  # Airリザーブ用プラグイン #############################################################
  - name: Airリザーブ
    file: airr

    # ログイン情報
    user: "**YourUser**"            # ログイン用ユーザ
    pass: "**YourPass**"            # ログイン用パスワード

    # 検索範囲(当日～n日後まで)
    range: 3
    
    # 検索対象のグループ
    group:
      - 江戸
      - 大阪
    # ルームリソース
    roomres:
      - 合議室
      - 帝鑑之間
      - 連歌之間
      - 不使用

    # 追加/削除をするかの設定
    skipadd: 0  # 1なら追加処理をスキップ
    skipdel: 0  # 1なら削除処理をスキップ

    # 追加削除前に確認するかの設定
    waitadd: 1  # 1なら追加の確定前に確認
    waitdel: 1  # 1なら削除の確定前に確認

    # 追加時のメニュー、セイ
    addmenu:  サイボウズ
    addsei:   ・ # 全角カナか「・」しか入力できない

    # 削除処理時の選択
    delreason: 店舗都合

# 同期処理用プラグイン
sync:
  # サイボウズ→Airリザーブ同期用プラグイン #####################################################
  - name:  マージ処理
    file:  cb2ar

    # 事務所と部屋の対応付け(左の部屋名はサイボウズ名、右の部屋名はAirリザーブ名)
    # 事務所名は、Airリザーブで検索できる名前であること
    room:
      帝鑑:     [江戸, 帝鑑之間]
      連歌:     [江戸, 連歌之間]
      煙草部屋: [大阪, 合議室]


    # 事務所と人の対応付け (左はサイボウズのsplitで取得できる空白文字までの名前)
    # 人の名前は(roomと異なり)サイボウズとAirリザーブで一致するため、追加情報は不要
    person:
      徳川: 江戸
      井伊: 江戸
      豊臣: 大阪
      織田: 岐阜


    # 以下の人は、部屋予約が不要な場合はAirリザーブに登録しない
    # ※部屋予約が不要 → eject対象外の誰かと共通の会議を持ち、その人が部屋を確保している場合
    eject:
      - 明智

    # 人/部屋と事務所のマッチングができなかった時の選択肢
    noroom:   不使用
    noperson: 無人

    # 無視する予定。サイボウズの予定名から正規表現で一致するものを無視。
    skipdesc: ".*（仮予定）.*"

    # 削除扱いの予定。サイボウズの予定名の先頭一致で指定。(無視と扱いは同等)
    deldesc:
      - 日程変更
      - キャンセル

    # 自動入力したときのキーワード(addmenuと同じで良い)
    automenu:  サイボウズ

     # 予約比較方法
    compdesc: 1 # 0:開始時刻/終了時刻/人/場所のみ比較、1:左記に加えてdescription(最大先頭40文字)まで含める

    
# その他オプション ####################################################################
keepdriver:     1 # ブラウザをプログラム開始～終了まで常駐したままにする(0:プラグインごとに必要に応じて起動)
skipget:        0 # 取得処理をスキップして保存されたマージファイルを解析(デバッグ用)
