# サンプルファイルです。個別に設定してください。
# カレンダ定義
cals:
  # サイボウズ用プラグイン ###############################################################
  - name: サイボウズ
    file: cybozu

    # ログイン情報
    serv: "**YourServer**"          # ログインサーバ名
    user: "**YourUser**"            # ログイン用ユーザ
    pass: "**YourPass**"            # ログイン用パスワード

    # 検索週範囲(当日～n日後まで)
    range: 3
    
    # 時刻がなくても、予定文が以下のいずれかと先頭一致なら終日扱い
    allday:
      - 休み
    alltime: 10:00-22:00

    # 検索対象のグループ(vlueはカレンダHTMLページ内の対応するOption-Valueを指定)
    group:
      - name: "拠点"
        value: "f" # <option value="f">拠点</option>
        target:
        - 江戸
        - 畿内
        - 岐阜
      - name: 担当者
        value: "123" # <option value="123">担当者</option>
        target:
        - 徳川
        - 豊臣
        - 織田

  # Airリザーブ用プラグイン #############################################################
  - name: Airリザーブ
    file: airr

    # ログイン情報
    user: "**YourUser**"            # ログイン用ユーザ
    pass: "**YourPass**"             # ログイン用パスワード

    # 検索週範囲(当日～n日後まで)
    range: 3
    
    # 検索対象のグループ
    group:
      - 江戸
      - 畿内

    # 削除処理時の選択
    delreason: 店舗都合

    # 追加時のメニュー、セイ
    addmenu:  サイボウズ
    addsei:   "・" # 「全角カナ」か「・」しか入力できない

# マージ処理用プラグイン
merge:
  # サイボウズ→Airリザーブ変換用プラグイン #####################################################
  - name:  マージ処理
    file:  cb2ar

    # 事務所と部屋の対応付け(左の部屋名はサイボウズ名、右の部屋名はAirリザーブ名)
    # 事務所名は、Airリザーブで検索できる名前であること
    room:
      会議室１:     [江戸, 会議]
      御殿１:       [大阪, 御殿]
      天守閣１:     [岐阜,  天守閣]

    roomcheck:
      - 会議
      - 御殿
      - 天守閣
      - 不使用

    # 事務所と人の対応付け (左はサイボウズのsplitで取得できる空白文字までの名前)
    # 人の名前は(roomと異なり)サイボウズとAirリザーブで一致するため、追加情報は不要
    person:
      徳川: 江戸
      豊臣: 大阪
      織田: 岐阜

    # 以下の人は、部屋予約が不要な場合はAirリザーブに登録しない
    # ※部屋予約が不要 → eject対象外の誰かと共通の会議を持ち、その人が部屋を確保している場合
    eject:
      - 明智

    # 人/部屋と事務所のマッチングができなかった時の選択肢
    noroom:   不使用
    noperson: 無人

    # サイボウズのタイトル（全角変換後）が以下に一致する場合はAirリザーブに入れない
    skipdesc: ".*（仮Ａ）.*"

    # 削除扱いの予定(先頭文字列)
    deldesc:
      - 日程変更
      - キャンセル

     # 予約比較方法
    compdesc: 0 # 0:開始時刻/終了時刻/人/場所のみ比較、1:左記に加えてdescription(最大先頭20文字)まで含める

    
# その他オプション ####################################################################
keep:     1 # ブラウザを常駐したままにする
skipget:  0 # 取得処理をスキップして保存されたマージファイルを解析(デバッグ用)
